#!/bin/sh

/usr/bin/dconf update

if [ "$MIC_RUN" != "" ]; then
    # exit with error to run again on first boot, just in case
    # ideally it won't do anything at that time because none of
    # key file mtimes have changed
    echo "dconf-update - returning FAIL to postpone oneshot to first boot"
    exit 1
fi
